workaround for building Linux < 4.11 with gcc >= 7
Symptoms:

kernel/built-in.o: In function `update_wall_time':
(.text+0x5acc6): undefined reference to `____ilog2_NaN'

This commit includes the workaround patch from the upstream Linux
kernel. Ideally, we would switch to a newer Linux version for the kvm
flavor. But this is quicker this way.

See:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=72785
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=474c90156c8dcc2fa815e6716cc9394d7930cb9c