selinux: Update to latest
Update the selinux package to the latest available.  Moves selinux
from pkg/selinux to vendor/github.com/opencontainers/selinux.

Fixes 'make unit-check' errors like these when a directory named
'/sys/fs/selinux' exists, but selinux is not enabled:

  --- FAIL: TestSetfilecon (0.00s)
        selinux_test.go: Setfilecon failed
        selinux_test.go: operation not supported

Signed-off-by: Geoff Levand <geoff@infradead.org>