stage1: integrate /diagexec wrapper into rkt run
Use /diagexec for launching the container's apps to assist understanding
execution interpreter problems.  No substantial overhead is introduced in the
normal/success case, diagnostics are only attempted when execv() of the target
fails.

Examples of the assistance provided:

  ~# bin/rkt run imgs/nobash.aci # bash script without /bin/bash
  Error: Unable to open "/bin/bash": No such file or directory
  Sending SIGTERM to remaining processes...
  Sending SIGKILL to remaining processes...
  Unmounting file systems.
  Unmounting /proc/sys/kernel/random/boot_id.
  All filesystems unmounted.
  Halting system.

  ~# bin/rkt run imgs/noexec.aci # file with no execute bits
  Error: "/noexec.sh" is not executable
  Sending SIGTERM to remaining processes...
  Sending SIGKILL to remaining processes...
  Unmounting file systems.
  Unmounting /proc/sys/kernel/random/boot_id.
  All filesystems unmounted.
  Halting system.

  ~# bin/rkt run imgs/noldlinux.aci # ELF program without interp
  Error: Unable to open "/lib64/ld-linux-x86-64.so.2": No such file or directory
  Sending SIGTERM to remaining processes...
  Sending SIGKILL to remaining processes...
  Unmounting file systems.
  Unmounting /proc/sys/kernel/random/boot_id.
  All filesystems unmounted.
  Halting system.

  ~# bin/rkt run imgs/noldlinuxbash.aci # script with bash without ELF interp
  Error: Unable to open "/lib64/ld-linux-x86-64.so.2": No such file or directory
  Sending SIGTERM to remaining processes...
  Sending SIGKILL to remaining processes...
  Unmounting file systems.
  Unmounting /proc/sys/kernel/random/boot_id.
  All filesystems unmounted.
  Halting system.

 Fixes #286